# Mapping entre les fichiers générés dans output/listes/ et les listes mail OVH.
#
# Seuls les fichiers listés ici sont synchronisés par ./sync_list.sh

# Membres
membres.csv=membres
nouveaux.csv=nouveaux
reinscrits.csv=reinscrits

# Pôles
Accueil_autonomie_des_nouveaux_et_formations.csv=autonomie-nouveaux
Communication.csv=communication
Escalade_pour_tous.csv=escalade-pour-tous
Évènements.csv=evenements
Informatique.csv=informatique
SAE_Vie_du_mur.csv=sae
Ski_de_rando.csv=ski-de-rando
Sorties.csv=sorties

# Enfants
parents.csv=parents
parents_mardi.csv=parents-mardi
parents_vendredi.csv=parents-vendredi
Encadrements_Enfants.csv=animsenfants

